-- 포스트 테이블
CREATE TABLE POST (
POST_NO NUMBER PRIMARY KEY,
POST_ID REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
POST_SUB VARCHAR2(6) DEFAULT '일반' CHECK(POST_SUB IN('공지','일반','정보','질문')),
POST_TITLE VARCHAR2(300) NOT NULL,
POST_CONTENT VARCHAR2(4000) NOT NULL,
POST_DATE DATE DEFAULT SYSDATE NOT NULL,
POST_HITS NUMBER DEFAULT 0 NOT NULL,
REPLY_COUNT NUMBER DEFAULT 0 NOT NULL,
SUPER_NO NOT NULL REFERENCES POST(POST_NO) ON DELETE CASCADE;
GROUP_NO NUMBER NOT NULL;
DEPTH NUMBER NOT NULL;
);

-- 게시번호 시퀀스
CREATE SEQUENCE POST_SEQ NOCACHE;
DROP SEQUENCE POST_SEQ;

-- 테스트 데이터 삽입
INSERT INTO POST VALUES(POST_NO_SEQ.NEXTVAL, 'master' , '공지' ,'공지사항 테스트','공지사항 테스트',SYSDATE , 0);

SELECT * FROM POST ORDER BY post_NO asc;
DROP TABLE POST;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='POST';

SELECT * FROM POST WHERE INSTR(POST_TITLE, '공지' ) > 0 AND POST_SUB = '공지';

INSERT INTO POST VALUES(POST_NO_SEQ.NEXTVAL, 'master' , '일반' , '테스트' , '테스트' , SYSDATE , 0);
UPDATE POST SET POST_HITS = 12 WHERE POST_NO = 1;

SELECT * FROM POST WHERE INSTR(POST_ID,'ter') > 0 ORDER BY POST_ID ASC, POST_DATE DESC;

UPDATE POST SET POST_HITS = 30 WHERE POST_NO = 1;
SELECT POST_HITS FROM POST WHERE POST_NO = 1;
UPDATE POST SET POST_SUB = '정보' , POST_TITLE = '수정테스트' , POST_CONTENT = '수정 테스트 중' WHERE POST_NO = 2;

SELECT COUNT(*) FROM POST WHERE POST_ID = 'sample'; 

UPDATE POST SET POST_HITS = POST_HITS + 1 WHERE POST_NO = 31 AND POST_ID != 'master';

