-- 게시글 첨부 파일을 저장하기 위한 테이블 (댓글과 비슷)

-- 파일 번호 : 기본키
-- 파일 이름 : 사용자가 올린 이름 (실제 파일이름이 아님)
-- 파일 크기 : 숫자(long)
-- 파일 유형 : image / png 와 같은 형태
-- 게시글 번호 : 외래키 (ON DELETE CASCADE)

CREATE TABLE POST_FILE(
POST_FILE_NO NUMBER PRIMARY KEY,
POST_NO REFERENCES POST(POST_NO) ON DELETE CASCADE,
POST_FILE_NAME VARCHAR2(256) NOT NULL,
POST_FILE_TYPE VARCHAR2(10) NOT NULL,
POST_FILE_SIZE NUMBER NOT NULL CHECK(POST_FILE_SIZE > 0)
);



CREATE SEQUENCE POST_FILE_SEQ NOCACHE;

-- 테이블 조회
SELECT * FROM POST_FILE;
SELECT * FROM MEMBER;
-- 그룹 쿼리 : 데이터를 그룹화하여 출력하기 위한 명령(쿼리)
-- 회원 등급별 인원수 출력
SELECT MEMBER_ID, COUNT(*) FROM MEMBER GROUP BY MEMBER_ID;
-- HAVING 개수 이상만 출력
SELECT ACCESS_AUTH, COUNT(*) FROM MEMBER_ACCESS GROUP BY ACCESS_AUTH HAVING COUNT(*) > 2;
-- 날짜별 회원 가입 현황(기준 > ACCESS_JOIN)
-- VIEW 만들기
CREATE OR REPLACE VIEW MEMBER_JOIN AS
SELECT 
	TO_CHAR(ACCESS_JOIN, 'YYYY-MM-DD') join, 
	COUNT(*) count 
FROM MEMBER_ACCESS 
GROUP BY TO_CHAR(ACCESS_JOIN , 'YYYY-MM-DD') 
ORDER BY join DESC;

DROP VIEW MEMBER_JOIN;
SELECT * FROM MEMBER_JOIN;
