-- 댓글 테이블 생성
CREATE TABLE REPLY(
REPLY_NO NUMBER PRIMARY KEY,
POST_NO REFERENCES POST(POST_NO) ON DELETE CASCADE,
REPLY_ID REFERENCES MEMBER(MEMBER_ID) ON DELETE SET NULL,
REPLY_CONTENT VARCHAR2(4000) NOT NULL,
REPLY_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- 댓글 번호 시퀀스 생성
CREATE SEQUENCE REPLY_SEQ NOCACHE;

-- 댓글 테이블 / 시퀀스 삭세
DROP SEQUENCE REPLY_SEQ;
DROP TABLE REPLY;

-- 댓글 테이블 조회
SELECT * FROM REPLY ORDER BY REPLY_NO DESC;

-- 댓글 시퀀스 조회해서 이 번호 넣기
SELECT REPLY_SEQ.NEXTVAL FROM DUAL;

-- 댓글 데이터 삽입 / 삭제 / 조회
INSERT INTO REPLY VALUES(1,62,'master','하이',SYSDATE);
DELETE REPLY WHERE REPLY_NO = 1;
SELECT * FROM REPLY WHERE POST_NO = 1 ORDER BY REPLY_DATE DESC;
SELECT COUNT(*) FROM REPLY WHERE POST_NO = 61;
UPDATE REPLY SET REPLY_CONTENT = '사랑해' WHERE POST_NO = 63 AND REPLY_NO = 13;
SELECT * FROM REPLY WHERE REPLY_ID = 'test01'  ORDER BY POST_NO DESC;